
services:
  ocelotgateway:
    container_name: ocelotgateway
    image: ocelotgatwayapp:latest
    build:
      context: .
      dockerfile: OcelotGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5243:8000
    networks:
      - ocelot-shared-network

networks:
  ocelot-shared-network:
    external: true